//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api_cargo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActiveRoute
    {
        public int active_route_id { get; set; }
        public int driver_id { get; set; }
        public int route_id { get; set; }
        public Nullable<System.DateTime> departure_date { get; set; }
        public Nullable<System.DateTime> arrival_date { get; set; }
        public Nullable<decimal> base_fare { get; set; }
    
        public virtual Driver Driver { get; set; }
        public virtual Routes Routes { get; set; }
    }
}
