//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api_cargo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admin
    {
        public Admin()
        {
            this.ChatThreads = new HashSet<ChatThreads>();
            this.UserSuspensions = new HashSet<UserSuspensions>();
        }
    
        public int admin_id { get; set; }
        public int user_id { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string CNIC { get; set; }
        public string contact_no { get; set; }
        public string street_no { get; set; }
        public string city { get; set; }
    
        public virtual Users Users { get; set; }
        public virtual ICollection<ChatThreads> ChatThreads { get; set; }
        public virtual ICollection<UserSuspensions> UserSuspensions { get; set; }
    }
}
