//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api_cargo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bookings
    {
        public int booking_id { get; set; }
        public int shipment_id { get; set; }
        public int customer_id { get; set; }
        public int route_id { get; set; }
        public Nullable<int> trip_id { get; set; }
        public string status { get; set; }
        public Nullable<decimal> amount { get; set; }
        public string cancel_reason { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public string booking_type { get; set; }
        public Nullable<System.DateTime> pickup_date { get; set; }
        public Nullable<System.DateTime> delivery_date { get; set; }
        public Nullable<System.DateTime> estimated_delivery_datetime { get; set; }
        public Nullable<System.DateTime> actual_delivery_datetime { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Routes Routes { get; set; }
        public virtual Shipments Shipments { get; set; }
        public virtual Trips Trips { get; set; }
    }
}
