//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api_cargo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChatAttachments
    {
        public int attachment_id { get; set; }
        public int message_id { get; set; }
        public string file_url { get; set; }
        public string file_type { get; set; }
        public Nullable<System.DateTime> uploaded_at { get; set; }
    
        public virtual ChatMessages ChatMessages { get; set; }
    }
}
