//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api_cargo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChatMessages
    {
        public ChatMessages()
        {
            this.ChatAttachments = new HashSet<ChatAttachments>();
        }
    
        public int message_id { get; set; }
        public int thread_id { get; set; }
        public int sender_user_id { get; set; }
        public string message_text { get; set; }
        public Nullable<bool> is_read { get; set; }
        public Nullable<System.DateTime> sent_at { get; set; }
    
        public virtual ICollection<ChatAttachments> ChatAttachments { get; set; }
        public virtual Users Users { get; set; }
        public virtual ChatThreads ChatThreads { get; set; }
    }
}
