//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api_cargo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChatThreads
    {
        public ChatThreads()
        {
            this.ChatMessages = new HashSet<ChatMessages>();
        }
    
        public int thread_id { get; set; }
        public string thread_type { get; set; }
        public Nullable<int> shipment_id { get; set; }
        public int created_by_user_id { get; set; }
        public Nullable<int> assigned_admin_id { get; set; }
        public string status { get; set; }
    
        public virtual Admin Admin { get; set; }
        public virtual ICollection<ChatMessages> ChatMessages { get; set; }
        public virtual Users Users { get; set; }
        public virtual Shipments Shipments { get; set; }
    }
}
