//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api_cargo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChatThreads
    {
        public ChatThreads()
        {
            this.ChatMessages = new HashSet<ChatMessages>();
        }
    
        public int thread_id { get; set; }
        public int customer_user_id { get; set; }
        public int driver_user_id { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
    
        public virtual ICollection<ChatMessages> ChatMessages { get; set; }
    }
}
