//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api_cargo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Checkpoints
    {
        public Checkpoints()
        {
            this.RouteCheckpoints = new HashSet<RouteCheckpoints>();
            this.Routes = new HashSet<Routes>();
            this.Routes1 = new HashSet<Routes>();
            this.Shipments = new HashSet<Shipments>();
            this.Shipments1 = new HashSet<Shipments>();
            this.TripCheckpoints = new HashSet<TripCheckpoints>();
        }
    
        public int checkpoint_id { get; set; }
        public string name { get; set; }
        public string location { get; set; }
        public Nullable<double> latitude { get; set; }
        public Nullable<double> longitude { get; set; }
        public Nullable<bool> is_active { get; set; }
    
        public virtual ICollection<RouteCheckpoints> RouteCheckpoints { get; set; }
        public virtual ICollection<Routes> Routes { get; set; }
        public virtual ICollection<Routes> Routes1 { get; set; }
        public virtual ICollection<Shipments> Shipments { get; set; }
        public virtual ICollection<Shipments> Shipments1 { get; set; }
        public virtual ICollection<TripCheckpoints> TripCheckpoints { get; set; }
    }
}
