//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api_cargo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Checkpoints
    {
        public Checkpoints()
        {
            this.TripCheckpoints = new HashSet<TripCheckpoints>();
        }
    
        public int checkpoint_id { get; set; }
        public string name { get; set; }
        public Nullable<double> latitude { get; set; }
        public Nullable<double> longitude { get; set; }
        public Nullable<int> driver_id { get; set; }
        public Nullable<int> route_id { get; set; }
        public Nullable<int> sequence_no { get; set; }
        public bool reached { get; set; }
    
        public virtual ICollection<TripCheckpoints> TripCheckpoints { get; set; }
        public virtual Driver Driver { get; set; }
        public virtual Routes Routes { get; set; }
    }
}
