//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api_cargo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DriverDocuments
    {
        public int document_id { get; set; }
        public int driver_id { get; set; }
        public Nullable<System.DateTime> uploaded_at { get; set; }
        public string cnic_link { get; set; }
        public string license_link { get; set; }
        public string front_link { get; set; }
        public string back_link { get; set; }
        public string photo_link { get; set; }
    
        public virtual Driver Driver { get; set; }
    }
}
