//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api_cargo.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CargoConnectEntities3 : DbContext
    {
        public CargoConnectEntities3()
            : base("name=CargoConnectEntities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Admin> Admin { get; set; }
        public DbSet<Bookings> Bookings { get; set; }
        public DbSet<ChatAttachments> ChatAttachments { get; set; }
        public DbSet<ChatMessages> ChatMessages { get; set; }
        public DbSet<ChatThreads> ChatThreads { get; set; }
        public DbSet<Checkpoints> Checkpoints { get; set; }
        public DbSet<Customer> Customer { get; set; }
        public DbSet<Driver> Driver { get; set; }
        public DbSet<DriverDocuments> DriverDocuments { get; set; }
        public DbSet<Notifications> Notifications { get; set; }
        public DbSet<PackageAttributeMapping> PackageAttributeMapping { get; set; }
        public DbSet<PackageAttributes> PackageAttributes { get; set; }
        public DbSet<Packages> Packages { get; set; }
        public DbSet<RecipientDetails> RecipientDetails { get; set; }
        public DbSet<Requests> Requests { get; set; }
        public DbSet<Reviews> Reviews { get; set; }
        public DbSet<Roles> Roles { get; set; }
        public DbSet<Routes> Routes { get; set; }
        public DbSet<RouteSchedule> RouteSchedule { get; set; }
        public DbSet<Shipments> Shipments { get; set; }
        public DbSet<TripCheckpoints> TripCheckpoints { get; set; }
        public DbSet<TripDelays> TripDelays { get; set; }
        public DbSet<Trips> Trips { get; set; }
        public DbSet<TripStats> TripStats { get; set; }
        public DbSet<Users> Users { get; set; }
        public DbSet<UserSuspensions> UserSuspensions { get; set; }
        public DbSet<Vehicle> Vehicle { get; set; }
        public DbSet<VehicleDocuments> VehicleDocuments { get; set; }
    }
}
