//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api_cargo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notifications
    {
        public int notification_id { get; set; }
        public int user_id { get; set; }
        public string title { get; set; }
        public string message { get; set; }
        public string related_entity_type { get; set; }
        public Nullable<int> related_entity_id { get; set; }
        public Nullable<bool> is_read { get; set; }
        public Nullable<System.DateTime> read_at { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
