//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api_cargo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PackageAttributeMapping
    {
        public int mapping_id { get; set; }
        public int package_id { get; set; }
        public int attribute_id { get; set; }
    
        public virtual PackageAttributes PackageAttributes { get; set; }
        public virtual Packages Packages { get; set; }
    }
}
