//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api_cargo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Packages
    {
        public Packages()
        {
            this.PackageAttributeMapping = new HashSet<PackageAttributeMapping>();
        }
    
        public int package_id { get; set; }
        public int shipment_id { get; set; }
        public string name { get; set; }
        public Nullable<double> weight { get; set; }
        public Nullable<double> length { get; set; }
        public Nullable<double> width { get; set; }
        public Nullable<double> height { get; set; }
        public Nullable<int> quantity { get; set; }
        public string color { get; set; }
        public string tagNo { get; set; }
    
        public virtual ICollection<PackageAttributeMapping> PackageAttributeMapping { get; set; }
        public virtual Shipments Shipments { get; set; }
    }
}
