//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api_cargo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecipientDetails
    {
        public int recipient_detail_id { get; set; }
        public int shipment_id { get; set; }
        public string recipient_fname { get; set; }
        public string recipient_lname { get; set; }
        public string recipient_contact { get; set; }
        public string instructionsMessage { get; set; }
    
        public virtual Shipments Shipments { get; set; }
    }
}
