//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api_cargo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Requests
    {
        public int request_id { get; set; }
        public int shipment_id { get; set; }
        public int driver_id { get; set; }
        public string status { get; set; }
    
        public virtual Driver Driver { get; set; }
        public virtual Shipments Shipments { get; set; }
    }
}
