//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api_cargo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reviews
    {
        public int review_id { get; set; }
        public int trip_id { get; set; }
        public int reviewer_user_id { get; set; }
        public int target_user_id { get; set; }
        public Nullable<int> rating { get; set; }
        public string comments { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
    
        public virtual Users Users { get; set; }
        public virtual Users Users1 { get; set; }
        public virtual Trips Trips { get; set; }
    }
}
