//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api_cargo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoutePreferences
    {
        public int id { get; set; }
        public int route_id { get; set; }
        public Nullable<bool> is_fragile { get; set; }
        public Nullable<bool> is_liquid { get; set; }
        public Nullable<bool> is_flammable { get; set; }
        public Nullable<bool> keep_upright { get; set; }
        public string shipment_type { get; set; }
    
        public virtual Routes Routes { get; set; }
    }
}
