//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api_cargo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RouteCheckpoints
    {
        public int route_detail_id { get; set; }
        public int route_id { get; set; }
        public int checkpoint_id { get; set; }
        public Nullable<int> sequence_no { get; set; }
        public Nullable<bool> reached { get; set; }
    
        public virtual Checkpoints Checkpoints { get; set; }
        public virtual Routes Routes { get; set; }
    }
}
