//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api_cargo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RouteSchedule
    {
        public int routeScheduleId { get; set; }
        public int route_id { get; set; }
        public string departureDate { get; set; }
        public string arrivalDate { get; set; }
    
        public virtual Routes Routes { get; set; }
    }
}
