//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api_cargo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Routes
    {
        public Routes()
        {
            this.ActiveRoute = new HashSet<ActiveRoute>();
            this.Bookings = new HashSet<Bookings>();
            this.NextRoute = new HashSet<NextRoute>();
            this.RouteCheckpoints = new HashSet<RouteCheckpoints>();
            this.Trips = new HashSet<Trips>();
        }
    
        public int route_id { get; set; }
        public int driver_id { get; set; }
        public int from_checkpoint { get; set; }
        public int to_checkpoint { get; set; }
        public Nullable<double> distance_km { get; set; }
    
        public virtual ICollection<ActiveRoute> ActiveRoute { get; set; }
        public virtual ICollection<Bookings> Bookings { get; set; }
        public virtual Checkpoints Checkpoints { get; set; }
        public virtual Checkpoints Checkpoints1 { get; set; }
        public virtual Driver Driver { get; set; }
        public virtual ICollection<NextRoute> NextRoute { get; set; }
        public virtual ICollection<RouteCheckpoints> RouteCheckpoints { get; set; }
        public virtual ICollection<Trips> Trips { get; set; }
    }
}
