//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api_cargo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Routes
    {
        public Routes()
        {
            this.Bookings = new HashSet<Bookings>();
            this.Checkpoints = new HashSet<Checkpoints>();
            this.Trips = new HashSet<Trips>();
            this.RouteSchedule = new HashSet<RouteSchedule>();
        }
    
        public int route_id { get; set; }
        public int driver_id { get; set; }
        public Nullable<bool> is_active { get; set; }
        public Nullable<bool> is_next_route { get; set; }
    
        public virtual ICollection<Bookings> Bookings { get; set; }
        public virtual ICollection<Checkpoints> Checkpoints { get; set; }
        public virtual Driver Driver { get; set; }
        public virtual ICollection<Trips> Trips { get; set; }
        public virtual ICollection<RouteSchedule> RouteSchedule { get; set; }
    }
}
