//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api_cargo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shipments
    {
        public Shipments()
        {
            this.Bookings = new HashSet<Bookings>();
            this.ChatThreads = new HashSet<ChatThreads>();
            this.Packages = new HashSet<Packages>();
            this.RecipientDetails = new HashSet<RecipientDetails>();
            this.Requests = new HashSet<Requests>();
            this.Trips = new HashSet<Trips>();
        }
    
        public int shipment_id { get; set; }
        public string sender_name { get; set; }
        public string sender_contact { get; set; }
        public string status { get; set; }
        public Nullable<int> pickup_checkpoint { get; set; }
        public Nullable<int> delivery_checkpoint { get; set; }
        public int customer_id { get; set; }
        public Nullable<bool> strict { get; set; }
        public Nullable<int> package_count { get; set; }
        public Nullable<double> total_weight { get; set; }
    
        public virtual ICollection<Bookings> Bookings { get; set; }
        public virtual ICollection<ChatThreads> ChatThreads { get; set; }
        public virtual Checkpoints Checkpoints { get; set; }
        public virtual Checkpoints Checkpoints1 { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual ICollection<Packages> Packages { get; set; }
        public virtual ICollection<RecipientDetails> RecipientDetails { get; set; }
        public virtual ICollection<Requests> Requests { get; set; }
        public virtual ICollection<Trips> Trips { get; set; }
    }
}
