//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api_cargo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TripDelays
    {
        public int delay_id { get; set; }
        public int trip_id { get; set; }
        public Nullable<System.DateTime> expected_delivery_date { get; set; }
        public Nullable<System.TimeSpan> expected_delivery_time { get; set; }
        public string reason { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
    
        public virtual Trips Trips { get; set; }
    }
}
