//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api_cargo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trips
    {
        public Trips()
        {
            this.Bookings = new HashSet<Bookings>();
            this.Reviews = new HashSet<Reviews>();
            this.TripCheckpoints = new HashSet<TripCheckpoints>();
            this.TripDelays = new HashSet<TripDelays>();
            this.TripStats = new HashSet<TripStats>();
        }
    
        public int trip_id { get; set; }
        public int shipment_id { get; set; }
        public int driver_id { get; set; }
        public string vehicle_reg_no { get; set; }
        public int route_id { get; set; }
        public Nullable<System.DateTime> start_time { get; set; }
        public Nullable<System.DateTime> end_time { get; set; }
        public string status { get; set; }
    
        public virtual ICollection<Bookings> Bookings { get; set; }
        public virtual Driver Driver { get; set; }
        public virtual ICollection<Reviews> Reviews { get; set; }
        public virtual Routes Routes { get; set; }
        public virtual Shipments Shipments { get; set; }
        public virtual ICollection<TripCheckpoints> TripCheckpoints { get; set; }
        public virtual ICollection<TripDelays> TripDelays { get; set; }
        public virtual Vehicle Vehicle { get; set; }
        public virtual ICollection<TripStats> TripStats { get; set; }
    }
}
