//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api_cargo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TripCheckpoints
    {
        public int checkpoint_event_id { get; set; }
        public int trip_id { get; set; }
        public int checkpoint_id { get; set; }
        public Nullable<System.DateTime> reached_at { get; set; }
        public Nullable<int> sequence_no { get; set; }
    
        public virtual Checkpoints Checkpoints { get; set; }
        public virtual Trips Trips { get; set; }
    }
}
