//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api_cargo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehicle
    {
        public Vehicle()
        {
            this.Trips = new HashSet<Trips>();
            this.VehicleDocuments = new HashSet<VehicleDocuments>();
        }
    
        public string vehicle_reg_no { get; set; }
        public string model { get; set; }
        public string type { get; set; }
        public Nullable<double> weight_capacity { get; set; }
        public Nullable<double> length { get; set; }
        public Nullable<double> width { get; set; }
        public Nullable<double> height { get; set; }
        public Nullable<int> driver_id { get; set; }
    
        public virtual Driver Driver { get; set; }
        public virtual ICollection<Trips> Trips { get; set; }
        public virtual ICollection<VehicleDocuments> VehicleDocuments { get; set; }
    }
}
